Reduce warning in OpenCL SDK
KhronosGroup/OpenCL-SDK pull request #74
Opened 2023-04-11 13:36 UTC by pwisniewskimobica

I reduced the warnings by doing small changes in File.c
Mostly it was changing `fopen` occurances to `fopen_s`

2023-04-11 13:37 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/KhronosGroup/OpenCL-SDK?pullRequest=74) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/KhronosGroup/OpenCL-SDK?pullRequest=74) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/KhronosGroup/OpenCL-SDK?pullRequest=74) it.</sub>

2023-05-09 05:48 UTC, bashbaug requested changes
This doesn't work on Linux, unfortunately:

```sh
/home/bashbaug/git/opencl-sdk/lib/src/Utils/File.c:41:13: warning: implicit declaration of function ‘fopen_s’; did you mean ‘fopen’?
```

A typical way to fix warnings like these is to just define `_CRT_SECURE_NO_WARNINGS` for Windows builds.  See, for example:

https://github.com/KhronosGroup/OpenCL-CTS/blob/20afedbd4a656a36132bfc42bd7519c426a1fa49/CMakeLists.txt#L153

2023-05-09 05:52 UTC, bashbaug commented
Alternatively, if we really want to keep the "secure" versions, we could either:

1. Add ifdefs and use `fopen_s` on Windows and `fopen` otherwise.
2. Add wrapper functions (maybe even a macro?) that calls `fopen_s` on Windows and `fopen` otherwise.

2023-05-09 11:37 UTC, MathiasMagnus commented
I would be highly against using `_CRT_SECURE_NO_WARNINGS`. It may pass in the CTS (even there it's not a good way), but the utility libraries are meant to be just as infrastructure as the rest of the ecosystem, encouraging downstreams to consume it. I wouldn't want ultrasound machines or whatever to ship code with security warnings disabled. That is not how we should roll.

_(And yes, secure versions of CRT functions is a mess in ISO C. Microsoft implements them, but fail to define the macro that would allow detecting their presence. GCC has POSIX or vendor-specific solution pre-dating secure CRT and have no intention implementing them. Hooray!)_

2023-05-09 15:08 UTC, bashbaug commented
FWIW, `fopen_s` is [supposed to sometimes be in C11](https://en.cppreference.com/w/c/io/fopen), but I tried enabling C11 compilation for the OpenCL SDK...

```
set(CMAKE_C_STANDARD 11)
```

... and I still ended up with linker errors on Linux.

I think a wrapper function/macro for non-Windows compiles is going to be our best bet.  We could possibly refine this further based on things like `__STDC_LIB_EXT1__`, but I'm not sure if it's worth the work.

2023-05-10 17:54 UTC, pwisniewskimobica commented
@bashbaug I just recommit this.
With creating additional function like fopen_no_warnings() independable from platform there will be more changes in the code- thats why I propose this solution with #ifdef's
What you think?

2023-05-11 16:36 UTC, bashbaug requested changes
This is getting better but there is a new issue now.

We could also look at defining a wrapper or macro once, at the top of this file, vs. introducing multiple #ifdefs.

https://stackoverflow.com/questions/1513209/is-there-a-way-to-use-fopen-s-with-gcc-or-at-least-create-a-define-about-it

2023-05-11 21:32 UTC, pwisniewskimobica commented
@bashbaug Thanks for comments
I applied one of stack overflow solututions.
-->done

2023-05-12 15:11 UTC, MathiasMagnus commented
👍🏻 If it resembles the original enough, please attribute according to CC license. (refer to the reading a file implementation attributed in a CC-compliant fashion.)

2023-05-22 09:23 UTC, pwisniewskimobica commented
@MathiasMagnus 
CC license comment introduced
Thanks

2023-05-23 09:01 UTC, pwisniewskimobica commented
@MathiasMagnus @bashbaug 
A bit different define introduced.
Please take a look

2023-05-23 10:18 UTC, MathiasMagnus approved these changes
LGTM

2023-05-23 10:21 UTC, MathiasMagnus commented
MacOS is failing. `__unix` only is not a good descriminator.

2023-05-24 18:34 UTC, pwisniewskimobica commented
@MathiasMagnus in newest version is "#ifndef _WIN32"
CI passing for all configurations .
Regards

2023-05-30 16:01 UTC, merged