Fix warning sign compare
KhronosGroup/OpenCL-SDK pull request #80
Opened 2023-06-23 15:40 UTC by Bogumil-Sapinski-Mobica

2023-06-29 12:53 UTC, alycm commented on lib/include/CL/SDK/Image.hpp
> +        size_t width = 0, height = 0, pixel_size = 1;
Given there are changes below to `reinterpret_cast` these back to `int` in one location below is this the correct change?  Should the other side of whatever was triggering the warning be changed?

2023-07-10 08:23 UTC, MathiasMagnus requested changes
Mostly good, but the `sdk::Image` changes I'd need convincing about.

2023-07-11 11:35 UTC, Bogumil-Sapinski-Mobica commented
Hi @MathiasMagnus,
I have changed solution for warnings caused by comparing signed and unsigned ints. Please verify if this is ok for you.

2023-07-11 15:46 UTC, MathiasMagnus approved these changes

2023-09-12 15:48 UTC, bashbaug commented
Merging as discussed in the September 12th teleconference.  The CI failures are unrelated to these changes.

2023-09-12 15:48 UTC, merged